apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
data:
  TITLE: "LibreSpeed"
  MODE: "frontend"
  TELEMETRY: "true"
  ENABLE_ID_OBFUSCATION: "true"
  REDACT_IP_ADDRESSES: "false"
  WEBPORT: "80"
  DB_TYPE: "mysql"
  DB_USERNAME: "librespeed"
  DB_NAME: "librespeed"
  DB_HOSTNAME: "mysql"