apiVersion: v1
kind: Secret
metadata:
  name: librespeed-secret
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
type: Opaque
stringData:
  DB_PASSWORD: Not4SecureProduction
  PASSWORD: gimmeTheStats1337