apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db  
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Not4SecureProduction
  MYSQL_PASSWORD: Not4SecureProduction